# Generated by Django 5.0 on 2023-12-25 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_person_code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True, verbose_name='Is Person Code'),
        ),
    ]
